# Generated by Django 5.2.7 on 2026-01-30 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('kyc_threshold', 'KYC Transfer Threshold'), ('tac_expiry_hours', 'TAC Expiry Hours'), ('daily_limit', 'Daily Transfer Limit'), ('weekly_limit', 'Weekly Transfer Limit'), ('monthly_limit', 'Monthly Transfer Limit')], max_length=50, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setting_type'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_name', models.CharField(max_length=200)),
                ('destination_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_wallet', 'Mobile Wallet'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('destination_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_tac', 'Pending TAC Generation'), ('tac_generated', 'TAC Generated - Awaiting Manual Send'), ('tac_sent', 'TAC Sent to Client'), ('tac_verified', 'TAC Verified'), ('pending_settlement', 'Pending External Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('kyc_required', 'KYC Required')], default='pending_tac', max_length=20)),
                ('requires_kyc', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('tac_code', models.CharField(blank=True, max_length=6, null=True)),
                ('tac_generated_at', models.DateTimeField(blank=True, null=True)),
                ('tac_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tac_sent_at', models.DateTimeField(blank=True, null=True)),
                ('tac_verified_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tacs', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('created', 'Transfer Created'), ('tac_generated', 'TAC Generated'), ('tac_sent', 'TAC Sent'), ('tac_verified', 'TAC Verified'), ('status_change', 'Status Changed'), ('pending_settlement', 'Pending Settlement'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('admin_note', 'Admin Note')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='compliance.transferrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['account', 'status'], name='compliance__account_dd5443_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'created_at'], name='compliance__status_eab8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['tac_code'], name='compliance__tac_cod_56a7cf_idx'),
        ),
    ]
