# Generated by Django 5.2.7 on 2026-01-31 11:37

import compliance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='reference',
            field=models.CharField(default=compliance.models.generate_uuid_reference, max_length=50, unique=True),
        ),
    ]
