# Generated by Django 5.2.7 on 2026-01-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_add_uuid_primary_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='check',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='check',
            old_name='started_at',
            new_name='checked_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='check',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='check',
            name='description',
        ),
        migrations.RemoveField(
            model_name='check',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='check',
            name='name',
        ),
        migrations.RemoveField(
            model_name='check',
            name='result',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(default='audit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(default='system', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='matches_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_type',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='check',
            name='user_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(default='standard', max_length=255),
        ),
    ]
