# Generated by Django 5.2.7 on 2026-01-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_update_check_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-checked_at']},
        ),
    ]
