# Generated by Django 5.2.7 on 2026-01-21 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('email_verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_verification_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verification_attempts', models.IntegerField(default=0)),
                ('password_reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_attempts', models.IntegerField(default=0)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'indexes': [models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'), models.Index(fields=['email_verified'], name='accounts_ac_email_v_107e12_idx')],
            },
        ),
    ]
