# Generated by Django 5.2.7 on 2026-01-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='account',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('id_card', 'National ID Card'), ('driver_license', 'Driver License')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='income_range',
            field=models.CharField(blank=True, choices=[('<30000', 'Less than KES 30,000'), ('30000-50000', 'KES 30,000 - 50,000'), ('50000-75000', 'KES 50,000 - 75,000'), ('75000-100000', 'KES 75,000 - 100,000'), ('100000-150000', 'KES 100,000 - 150,000'), ('150000+', 'More than KES 150,000')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
