# Generated by Django 5.2.7 on 2026-01-30 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_address_remove_account_national_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='street',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='state',
            new_name='state_province',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('dormant', 'Dormant')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='activation_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='doc_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='account',
            name='doc_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='doc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='doc_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='account',
            name='doc_selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
        migrations.AddField(
            model_name='account',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('residence_permit', 'Residence Permit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('transgender', 'Transgender'), ('genderqueer', 'Genderqueer'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='income_range',
            field=models.CharField(blank=True, choices=[('<10000', 'Below $10,000 / €9,000 / £8,000'), ('10000-30000', '$10,000 - $30,000 / €9,000 - €27,000'), ('30000-50000', '$30,000 - $50,000 / €27,000 - €45,000'), ('50000-75000', '$50,000 - $75,000 / €45,000 - €68,000'), ('75000-100000', '$75,000 - $100,000 / €68,000 - €90,000'), ('100000-150000', '$100,000 - $150,000 / €90,000 - €135,000'), ('150000-200000', '$150,000 - $200,000 / €135,000 - €180,000'), ('>200000', 'Above $200,000 / €180,000 / £160,000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
