# Generated by Django 5.2.7 on 2026-01-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountsettings_account_and_more'),
    ]

    operations = [
    ]
