# Generated by Django 5.2.7
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20260103_0837'),
    ]
    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]