# Generated by Django 5.2.7 on 2026-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_set', related_query_name='account', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='income_range',
            field=models.CharField(blank=True, choices=[('<10000', 'Below $10,000 / â‚¬9,000 / Â£8,000'), ('10000-30000', '$10,000 - $30,000 / â‚¬9,000 - â‚¬27,000'), ('30000-50000', '$30,000 - $50,000 / â‚¬27,000 - â‚¬45,000'), ('50000-75000', '$50,000 - $75,000 / â‚¬45,000 - â‚¬68,000'), ('75000-100000', '$75,000 - $100,000 / â‚¬68,000 - â‚¬90,000'), ('100000-150000', '$100,000 - $150,000 / â‚¬90,000 - â‚¬135,000'), ('150000-200000', '$150,000 - $200,000 / â‚¬135,000 - â‚¬180,000'), ('>200000', 'Above $200,000 / â‚¬180,000 / Â£160,000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_set', related_query_name='account', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
