# Generated by Django 5.2.7 on 2026-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260103_0837'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password_reset_sent_at',
            new_name='email_verification_otp_sent_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='email_verification_sent_at',
            new_name='password_reset_otp_sent_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='account',
            name='email_verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password_reset_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email_verified'], name='accounts_ac_email_v_107e12_idx'),
        ),
    ]
