# Generated by Django 4.2.10 on 2026-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptotransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cryptotransaction',
                'verbose_name_plural': 'Cryptotransactions',
                'db_table': 'crypto_cryptotransaction',
            },
        ),
        migrations.CreateModel(
            name='Cryptowallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cryptowallet',
                'verbose_name_plural': 'Cryptowallets',
                'db_table': 'crypto_cryptowallet',
            },
        ),
    ]
