# Generated by Django 5.2.7 on 2026-01-16 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain', models.CharField(default='ethereum', max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('decimals', models.IntegerField(default=18)),
                ('current_price_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('change_24h', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('change_7d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('change_30d', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_tradable', models.BooleanField(default=True)),
                ('is_depositable', models.BooleanField(default=True)),
                ('is_withdrawable', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_withdrawal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('explorer_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-market_cap'],
                'indexes': [models.Index(fields=['symbol'], name='crypto_cryp_symbol_b08612_idx'), models.Index(fields=['is_active'], name='crypto_cryp_is_acti_72d80b_idx'), models.Index(fields=['blockchain'], name='crypto_cryp_blockch_0e8169_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('send', 'Send'), ('receive', 'Receive'), ('swap', 'Swap'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending_compliance', 'Pending Compliance'), ('compliance_approved', 'Compliance Approved'), ('compliance_rejected', 'Compliance Rejected')], default='pending', max_length=30)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('network_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_at_transaction', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('compliance_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_compliance_approval', models.BooleanField(default=False)),
                ('compliance_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('under_review', 'Under Review')], default='not_required', max_length=20)),
                ('is_high_value', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('compliance_notes', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=6)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_limit', models.BigIntegerField(blank=True, null=True)),
                ('swap_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crypto.cryptoasset')),
                ('swap_from_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_from_transactions', to='crypto.cryptoasset')),
                ('swap_to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_to_transactions', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoComplianceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('high_value', 'High Value Transaction'), ('new_address', 'Withdrawal to New Address'), ('suspicious_pattern', 'Suspicious Pattern'), ('aml_alert', 'AML Alert'), ('sanctions_match', 'Sanctions List Match'), ('pep_match', 'PEP (Politically Exposed Person)')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_flags', to='crypto.cryptotransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('wallet_type', models.CharField(choices=[('hot', 'Hot Wallet'), ('cold', 'Cold Wallet'), ('custodial', 'Custodial'), ('non_custodial', 'Non-Custodial')], default='hot', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('compliance_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_compliance_approval', models.BooleanField(default=False)),
                ('compliance_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('under_review', 'Under Review')], default='not_required', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('encrypted_private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('mnemonic_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='crypto.cryptowallet'),
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='crypto.cryptowallet'),
        ),
        migrations.CreateModel(
            name='CryptoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('wallet_created', 'Wallet Created'), ('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('compliance_requested', 'Compliance Requested'), ('compliance_approved', 'Compliance Approved'), ('compliance_rejected', 'Compliance Rejected'), ('flag_created', 'Compliance Flag Created'), ('flag_resolved', 'Compliance Flag Resolved'), ('kyc_requested', 'KYC Requested'), ('tac_generated', 'TAC Generated'), ('tac_verified', 'TAC Verified')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.cryptotransaction')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.cryptowallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['user', 'asset'], name='crypto_cryp_user_id_037bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['user', 'is_active'], name='crypto_cryp_user_id_f0a299_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['wallet_address'], name='crypto_cryp_wallet__fe999f_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['compliance_reference'], name='crypto_cryp_complia_e26d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['compliance_status'], name='crypto_cryp_complia_7162af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('user', 'asset')},
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['user', 'status'], name='crypto_cryp_user_id_a48319_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['user', 'created_at'], name='crypto_cryp_user_id_9a8cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['status', 'created_at'], name='crypto_cryp_status_219dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['transaction_hash'], name='crypto_cryp_transac_5afd71_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['compliance_reference'], name='crypto_cryp_complia_ce92b3_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['compliance_status'], name='crypto_cryp_complia_fbb661_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['is_high_value'], name='crypto_cryp_is_high_4c0e01_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['is_suspicious'], name='crypto_cryp_is_susp_f63be9_idx'),
        ),
    ]
