# Generated by Django 5.2.7 on 2026-01-21 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptowallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('litecoin', 'Litecoin'), ('tron', 'Tron')], default='bitcoin', max_length=20)),
                ('address', models.CharField(default='', max_length=255, unique=True)),
                ('private_key_encrypted', models.TextField(default='')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Wallet',
                'verbose_name_plural': 'Crypto Wallets',
                'db_table': 'crypto_cryptowallet',
            },
        ),
        migrations.CreateModel(
            name='Cryptotransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], default='deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('currency', models.CharField(default='BTC', max_length=10)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('from_address', models.CharField(default='', max_length=255)),
                ('to_address', models.CharField(default='', max_length=255)),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(blank=True, db_column='wallet_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptowallet')),
            ],
            options={
                'verbose_name': 'Crypto Transaction',
                'verbose_name_plural': 'Crypto Transactions',
                'db_table': 'crypto_cryptotransaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
