# Generated by Django 5.2.7 on 2026-01-21 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'crypto_cryptoasset',
            },
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='last_transaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='mnemonic_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='name',
            field=models.CharField(default='Crypto Wallet', max_length=255),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='wallet_address',
            field=models.CharField(default='temporary_wallet', max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='transaction_type',
            field=models.CharField(default='deposit', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='address',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='wallet_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.cryptoasset'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('user', 'asset')},
        ),
    ]
