# Generated by Django 5.2.7 on 2026-01-31 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('TRANSFER_INITIATED', 'Transfer Initiated'), ('TAC_SENT', 'TAC Sent to Email'), ('TAC_VERIFIED', 'TAC Verified'), ('TRANSFER_COMPLETED', 'Transfer Completed'), ('TRANSFER_FAILED', 'Transfer Failed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('ACCOUNT_CREATED', 'Account Created'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('ADMIN_PAYMENT_PROCESSED', 'Payment Processed (Admin)'), ('ADMIN_TAC_REQUIRED', 'TAC Required (Admin)'), ('ADMIN_TAC_GENERATED', 'TAC Generated (Admin)'), ('ADMIN_SETTLEMENT_REQUIRED', 'Settlement Required (Admin)'), ('ADMIN_KYC_REVIEW_REQUIRED', 'KYC Review Required (Admin)'), ('ADMIN_NEW_TRANSFER', 'New Transfer Request (Admin)')], default='PAYMENT_RECEIVED', max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='UNREAD', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, to_field='account_number')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed'), ('PUSH_SENT', 'Push Sent'), ('PUSH_FAILED', 'Push Failed'), ('READ', 'Marked as Read'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], max_length=20)),
                ('channel', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PUSH', 'Push'), ('IN_APP', 'In-App'), ('SMS', 'SMS')], max_length=20, null=True)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_high_priority', models.BooleanField(default=True)),
                ('email_medium_priority', models.BooleanField(default=True)),
                ('email_low_priority', models.BooleanField(default=False)),
                ('receive_payment_notifications', models.BooleanField(default=True)),
                ('receive_transfer_notifications', models.BooleanField(default=True)),
                ('receive_tac_notifications', models.BooleanField(default=True)),
                ('receive_account_notifications', models.BooleanField(default=True)),
                ('receive_admin_notifications', models.BooleanField(default=True)),
                ('immediate_delivery', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='18:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, to_field='account_number')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account', 'status'], name='notificatio_account_7d88e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_f7c359_idx'),
        ),
    ]
