# Generated by Django 5.2.7 on 2026-01-31 04:26
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_remove_notification_notificatio_account_7d88e6_idx_and_more'),
    ]

    operations = [
        # Only change the account field to use user_id column
        migrations.AlterField(
            model_name='notificationpreference',
            name='account',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notification_preferences',
                to=settings.AUTH_USER_MODEL,
                db_column='user_id'
            ),
        ),
    ]
