# Generated by Django 5.2.7 on 2026-02-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20260131_0426'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_account_7d88e6_idx',
        ),
    ]
