# Generated by Django 5.2.7 on 2026-02-02 15:33

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_notificatio_account_7d88e6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=notifications.models.ModelSafeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=notifications.models.ModelSafeJSONEncoder),
        ),
    ]
