# Generated by Django 5.2.7 on 2026-02-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='account',
        ),
    ]
