# Generated by Django 5.2.7 on 2025-12-26 21:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('updated', 'Updated'), ('funded', 'Funded'), ('released', 'Released'), ('disputed', 'Disputed')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='escrow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='escrow',
            old_name='reason',
            new_name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='sender',
        ),
        migrations.AddField(
            model_name='escrow',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='escrow',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_opened_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'No Dispute'), ('opened', 'Dispute Opened'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='escrow',
            name='escrow_id',
            field=models.CharField(default='No description', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='expected_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='escrow',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='escrow',
            name='receiver_id',
            field=models.CharField(db_index=True, default='No description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='release_approved_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='release_approved_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='sender_id',
            field=models.CharField(db_index=True, default='No description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='sender_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='escrow',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['sender_id', '-created_at'], name='escrow_escr_sender__0309b6_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['receiver_id', '-created_at'], name='escrow_escr_receive_9c35a5_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['escrow_id'], name='escrow_escr_escrow__5128c2_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status'], name='escrow_escr_status_f1ab5c_idx'),
        ),
        migrations.AddField(
            model_name='escrowlog',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='escrow.escrow'),
        ),
    ]
