# Generated by Django 5.2.7 on 2026-01-21 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TacCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=6, unique=True)),
                ('purpose', models.CharField(choices=[('verification', 'Verification'), ('withdrawal', 'Withdrawal'), ('login', 'Login'), ('transaction', 'Transaction')], default='verification', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tac_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAC Code',
                'verbose_name_plural': 'TAC Codes',
                'db_table': 'tac_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
