# Generated by Django 5.2.7 on 2026-01-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_missing_tables'),
    ]

    operations = [
    ]
