# Generated by Django 5.2.7 on 2026-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_fix_table_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='clavericatask',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='clavericatask',
            table='claverica_tasks_clavericatask',
        ),
        migrations.AlterModelTable(
            name='taskcategory',
            table='claverica_tasks_taskcategory',
        ),
        migrations.AlterModelTable(
            name='userrewardbalance',
            table='claverica_tasks_userrewardbalance',
        ),
        migrations.AlterModelTable(
            name='usertask',
            table='claverica_tasks_usertask',
        ),
    ]
