# Generated by Django 5.2.7 on 2026-01-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sync_with_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clavericatask',
            name='display_order',
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='color',
            field=models.CharField(default='#000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
