# Generated by Django 5.2.7 on 2026-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_fix_models_sync'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrewardbalance',
            old_name='withdrawn_balance',
            new_name='pending_balance',
        ),
        migrations.RenameField(
            model_name='userrewardbalance',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='name',
            field=models.CharField(default='User Balance', max_length=255),
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='tasks_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrewardbalance',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
