# Generated by Django 5.2.7 on 2026-01-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_fix_userrewardbalance_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrewardbalance',
            name='display_order',
        ),
    ]
