# Generated by Django 5.2.7 on 2026-01-30 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('transfer', 'Large Transfer'), ('loan', 'Loan Application'), ('escrow', 'Escrow Service'), ('savings', 'Savings Account'), ('crypto', 'Crypto Services'), ('card', 'Virtual Card')], max_length=50, unique=True)),
                ('requires_kyc', models.BooleanField(default=True)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=1500.0, help_text='Amount above which KYC is required', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Setting',
                'verbose_name_plural': 'KYC Settings',
                'db_table': 'kyc_settings',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('driver_license', 'Driver License'), ('passport', 'Passport')], default='national_id', max_length=50)),
                ('id_front_image', models.ImageField(upload_to='kyc/id_front/%Y/%m/%d/', verbose_name='ID Front')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='kyc/id_back/%Y/%m/%d/', verbose_name='ID Back')),
                ('facial_image', models.ImageField(upload_to='kyc/facial/%Y/%m/%d/', verbose_name='Facial Verification')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Reason for Rejection/Correction')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_documents',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('transfer', 'Large Transfer'), ('loan', 'Loan Application'), ('escrow', 'Escrow Service'), ('savings', 'Savings Account'), ('crypto', 'Crypto Services'), ('card', 'Virtual Card')], max_length=50)),
                ('requested_for', models.CharField(help_text='What service/feature requires KYC', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_triggered', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kyc_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.kycdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
