# Generated by Django 5.2.7 on 2026-01-21 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('destination_type', models.CharField(max_length=100)),
                ('destination_details', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('requires_tac', models.BooleanField()),
                ('tac_verified', models.BooleanField()),
                ('tac_code_id', models.CharField(blank=True, max_length=255, null=True)),
                ('kyc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('compliance_status', models.CharField(max_length=50)),
                ('processed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='Withdrawal Request', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
