# Generated by Django 5.2.7 on 2025-12-31 15:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('bank', 'Bank'), ('fintech', 'Fintech'), ('crypto', 'Cryptocurrency')], max_length=20)),
                ('name', models.CharField(help_text='Recipient name or institution', max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.CharField(default='🏦', help_text='Emoji or icon', max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, help_text='e.g., TRC20, ERC20, BTC', max_length=50, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('transfer_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('fintech', 'Fintech Transfer'), ('crypto', 'Crypto Transfer'), ('international', 'International Transfer'), ('internal', 'Internal Transfer')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('compliance_review', 'Compliance Review')], default='pending', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_tac', models.BooleanField(default=False, help_text='Requires Transfer Authorization Code')),
                ('tac_verified', models.BooleanField(default=False)),
                ('tac_verified_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_status', models.CharField(default='pending', help_text='KYC/AML status', max_length=50)),
                ('compliance_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_account', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='transfers.recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tac_codes', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tac_codes', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['user', 'recipient_type'], name='transfers_r_user_id_5f5993_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['is_favorite'], name='transfers_r_is_favo_848a27_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender', 'status'], name='transfers_t_sender__523e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_id'], name='transfers_t_transfe_ff5ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['created_at'], name='transfers_t_created_8236ff_idx'),
        ),
        migrations.AddIndex(
            model_name='taccode',
            index=models.Index(fields=['user', 'is_used'], name='transfers_t_user_id_bbe62b_idx'),
        ),
        migrations.AddIndex(
            model_name='taccode',
            index=models.Index(fields=['code'], name='transfers_t_code_319777_idx'),
        ),
    ]
