# Generated by Django 5.2.7 on 2026-01-16 18:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_account', models.CharField(max_length=100)),
                ('recipient_bank', models.CharField(blank=True, max_length=255)),
                ('recipient_country', models.CharField(blank=True, max_length=2)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('compliance_review', 'Compliance Review'), ('awaiting_tac', 'Awaiting TAC'), ('awaiting_video_call', 'Awaiting Video Call')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('tac_required', models.BooleanField(default=False)),
                ('tac_verified', models.BooleanField(default=False)),
                ('tac_verified_at', models.DateTimeField(blank=True, null=True)),
                ('video_call_required', models.BooleanField(default=False)),
                ('video_call_completed', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('compliance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='compliance.compliancerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('video_call_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='compliance.videocallsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('limit_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_transaction', 'Per Transaction'), ('lifetime', 'Lifetime')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_change', 'Status Change'), ('tac_generated', 'TAC Generated'), ('tac_verified', 'TAC Verified'), ('video_call_scheduled', 'Video Call Scheduled'), ('video_call_completed', 'Video Call Completed'), ('compliance_check', 'Compliance Check'), ('processed', 'Processed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_id'], name='transfers_t_transfe_ff5ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['user', 'created_at'], name='transfers_t_user_id_29fcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'created_at'], name='transfers_t_status_f3090c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['compliance_request'], name='transfers_t_complia_f88064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferlimit',
            unique_together={('user', 'country', 'currency', 'limit_type')},
        ),
    ]
