# Generated by Django 5.2.7 on 2026-02-02 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tac',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transfer',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tac_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tac_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 2, 11, 13, 52, 822230, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tac',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tac', to='transfers.transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferlimit',
            name='limit_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_transaction', 'Per Transaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='log_type',
            field=models.CharField(choices=[('created', 'Transfer Created'), ('tac_sent', 'TAC Sent'), ('tac_verified', 'TAC Verified'), ('funds_deducted', 'Funds Deducted'), ('settlement_completed', 'Settlement Completed'), ('status_change', 'Status Change'), ('error', 'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transfers.transfer'),
        ),
    ]
