# Generated by Django 5.2.7 on 2026-01-30 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Custom payment code like UASIP57EEO', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Can this payment code receive payments?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(help_text='Account that this payment code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Code',
                'verbose_name_plural': 'Payment Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount credited to account', max_digits=10)),
                ('sender', models.CharField(help_text="Sender name (e.g., 'ecovera')", max_length=255)),
                ('reference', models.CharField(help_text='Auto-generated reference like PAY-20260129-001', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', help_text='Payment status', max_length=20)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before payment', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after payment', max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account that received the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('payment_code', models.ForeignKey(blank=True, help_text='Payment code used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentcode')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='payments_pa_account_172f9e_idx'), models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'), models.Index(fields=['payment_code'], name='payments_pa_payment_945ee3_idx')],
            },
        ),
    ]
