# Generated by Django 5.2.7 on 2026-01-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
