# Generated by Django 5.2.7 on 2026-01-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Account balance after payment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Account balance before payment', max_digits=10),
        ),
    ]
