# Generated by Django 5.2.7 on 2026-01-21 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_details_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='ACC_0001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(default='visa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='last4',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='deposit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='account',
            table='payments_account',
        ),
        migrations.AlterModelTable(
            name='card',
            table='payments_card',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments_payment',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payments_paymentmethod',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='payments_transaction',
        ),
    ]
