# Generated by Django 5.2.7 on 2026-01-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_missing_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='last4',
            new_name='last_four',
        ),
    ]
