# Generated by Django 5.2.7 on 2026-02-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(default='uncategorized', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('receipt_data', models.JSONField(default=dict)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='receipts_re_categor_2c0f41_idx'), models.Index(fields=['status'], name='receipts_re_status_ce247e_idx'), models.Index(fields=['user', 'uploaded_at'], name='receipts_re_user_id_85e292_idx')],
            },
        ),
    ]
