# Generated by Django 5.2.7 on 2025-12-30 21:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('receiver_id', models.CharField(db_index=True, max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_released', models.BooleanField(default=False)),
                ('release_approved_by_sender', models.BooleanField(default=False)),
                ('release_approved_by_receiver', models.BooleanField(default=False)),
                ('dispute_status', models.CharField(choices=[('none', 'No Dispute'), ('opened', 'Dispute Opened'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='none', max_length=20)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('dispute_opened_by', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_opened_at', models.DateTimeField(blank=True, null=True)),
                ('expected_release_date', models.DateTimeField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender_id', '-created_at'], name='escrow_escr_sender__0309b6_idx'), models.Index(fields=['receiver_id', '-created_at'], name='escrow_escr_receive_9c35a5_idx'), models.Index(fields=['escrow_id'], name='escrow_escr_escrow__5128c2_idx'), models.Index(fields=['status'], name='escrow_escr_status_f1ab5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscrowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('updated', 'Updated'), ('funded', 'Funded'), ('released', 'Released'), ('disputed', 'Disputed')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='escrow.escrow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
