# Generated by Django 4.2.10 on 2026-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escrow',
                'verbose_name_plural': 'Escrows',
                'db_table': 'escrow_escrow',
            },
        ),
        migrations.CreateModel(
            name='Escrowlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escrowlog',
                'verbose_name_plural': 'Escrowlogs',
                'db_table': 'escrow_escrowlog',
            },
        ),
    ]
