# Generated by Django 5.2.7 on 2026-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='created_at',
        ),
        migrations.AddField(
            model_name='escrow',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='escrowlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escrowlog',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
