# Generated by Django 5.2.7 on 2026-01-21 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_remove_escrow_created_at_escrow_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AddField(
            model_name='escrow',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='receiver',
            field=models.CharField(blank=True, default='Unknown Receiver', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='sender',
            field=models.CharField(blank=True, default='Unknown Sender', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='name',
            field=models.CharField(default='Untitled Escrow', max_length=255),
        ),
    ]
