# Generated by Django 5.2.7 on 2026-01-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_complete_model_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='compliance_reference',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='dispute_opened_at',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='dispute_opened_by',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='dispute_status',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='escrow_id',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='expected_release_date',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='funded_at',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='release_approved_by_receiver',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='release_approved_by_sender',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='requires_compliance_approval',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='title',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
