# Generated by Django 5.2.7 on 2026-01-21 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_fix_boolean_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='release_approved_by_receiver',
        ),
        migrations.RemoveField(
            model_name='escrow',
            name='release_approved_by_sender',
        ),
        migrations.AddField(
            model_name='escrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='escrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterModelTable(
            name='escrow',
            table='escrow_escrow',
        ),
        migrations.DeleteModel(
            name='Escrowlog',
        ),
    ]
