# Generated by Django 5.2.7 on 2026-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_fix_model_minimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='escrow',
            name='compliance_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_opened_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='escrow',
            name='escrow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='expected_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='receiver_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='receiver_name',
            field=models.CharField(default='Unknown Receiver', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='release_approved_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='release_approved_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='requires_compliance_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='sender_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='sender_name',
            field=models.CharField(default='Unknown Sender', max_length=255),
        ),
        migrations.AddField(
            model_name='escrow',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
