# Generated by Django 5.2.7 on 2025-12-26 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=500)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('business', 'Business Expense'), ('personal', 'Personal Expense'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('food', 'Food & Dining'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='other', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', '-uploaded_at'], name='receipts_re_user_id_b8893d_idx'), models.Index(fields=['category'], name='receipts_re_categor_2c0f41_idx'), models.Index(fields=['status'], name='receipts_re_status_ce247e_idx')],
            },
        ),
    ]
