# Generated by Django 5.2.7 on 2025-12-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='user_id',
            field=models.CharField(db_index=True, default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('export', 'Exported')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('merchant', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('income', 'Income'), ('salary', 'Salary'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('food', 'Food & Dining'), ('travel', 'Travel'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['user_id', '-transaction_date'], name='transaction_user_id_64ff44_idx'), models.Index(fields=['transaction_id'], name='transaction_transac_fee96f_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['type'], name='transaction_type_dae97e_idx')],
            },
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['user_id', '-timestamp'], name='transaction_user_id_4be32d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['action'], name='transaction_action_6c818f_idx'),
        ),
    ]
