# Generated by Django 5.2.7 on 2026-02-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit (Payment Received)'), ('debit', 'Debit (Transfer Sent)'), ('fee', 'Service Fee'), ('refund', 'Refund'), ('payment_in', 'Payment Received'), ('transfer_out', 'Transfer Sent')], max_length=20),
        ),
    ]
