# Generated by Django 5.2.7 on 2026-01-21 07:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical')], default='virtual', max_length=10)),
                ('card_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('last_four', models.CharField(default='0000', max_length=4)),
                ('cvv', models.CharField(default='000', max_length=4)),
                ('expiry_date', models.CharField(default='01/30', max_length=5)),
                ('cardholder_name', models.CharField(default='Card Holder', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('spending_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('color_scheme', models.CharField(default='from-indigo-500 via-purple-500 to-pink-500', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cards_card_user_id_698812_idx'), models.Index(fields=['card_number'], name='cards_card_card_nu_0f279e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'is_primary'), name='unique_primary_card_per_user')],
            },
        ),
    ]
