# Generated by Django 5.2.7 on 2026-01-30 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical')], default='virtual', max_length=10)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('last_four', models.CharField(default='0000', max_length=4)),
                ('expiry_date', models.CharField(default='01/30', max_length=5)),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('color_scheme', models.CharField(default='blue-gradient', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
