# Generated by Django x.x on 2024-01-01 00:00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),  # This should match your first migration
        # If you're not sure, check what files exist in cards/migrations/
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='CardTransaction',
        ),
    ]