# Generated by Django 5.2.7 on 2026-01-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_transaction_to_cardtransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cardtransaction',
            new_name='cards_cardt_user_id_16d73e_idx',
            old_name='cards_trans_user_id_2b37b9_idx',
        ),
        migrations.RenameIndex(
            model_name='cardtransaction',
            new_name='cards_cardt_card_id_d4e9b9_idx',
            old_name='cards_trans_card_id_c7cfec_idx',
        ),
        migrations.RenameIndex(
            model_name='cardtransaction',
            new_name='cards_cardt_status_bf4e83_idx',
            old_name='cards_trans_status_9936ab_idx',
        ),
    ]
