# Generated by Django 5.2.7 on 2026-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
