# Generated by Django 4.2.10 on 2026-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksClavericatask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TasksClavericatask',
                'verbose_name_plural': 'TasksClavericatasks',
                'db_table': 'claverica_tasks_clavericatask',
            },
        ),
        migrations.CreateModel(
            name='TasksRewardwithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TasksRewardwithdrawal',
                'verbose_name_plural': 'TasksRewardwithdrawals',
                'db_table': 'claverica_tasks_rewardwithdrawal',
            },
        ),
        migrations.CreateModel(
            name='TasksTaskcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TasksTaskcategory',
                'verbose_name_plural': 'TasksTaskcategorys',
                'db_table': 'claverica_tasks_taskcategory',
            },
        ),
        migrations.CreateModel(
            name='TasksUserrewardbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TasksUserrewardbalance',
                'verbose_name_plural': 'TasksUserrewardbalances',
                'db_table': 'claverica_tasks_userrewardbalance',
            },
        ),
    ]
