# Generated by Django 5.2.7 on 2026-01-30 15:30

from django.db import migrations

def convert_account_numbers(apps, schema_editor):
    """
    Convert account_number foreign keys to account_id foreign keys.
    Old: account_number (string) -> Account.account_number
    New: account_id (integer) -> Account.id
    """
    Account = apps.get_model('accounts', 'Account')
    UserProfile = apps.get_model('users', 'UserProfile')
    UserSettings = apps.get_model('users', 'UserSettings')
    
    print("Converting account_number foreign keys to account_id...")
    
    # First, update UserSettings
    for settings in UserSettings.objects.all():
        try:
            # Get the account by account_number
            if hasattr(settings, 'account_number') and settings.account_number:
                account = Account.objects.get(account_number=settings.account_number)
                # Create new settings with correct foreign key
                settings.account = account
                settings.save()
                print(f"Updated UserSettings {settings.id}: {settings.account_number} -> Account {account.id}")
        except Account.DoesNotExist:
            print(f"Warning: No account found for UserSettings {settings.id} with account_number {settings.account_number}")
            # Delete orphaned settings
            settings.delete()
    
    # Then update UserProfile
    for profile in UserProfile.objects.all():
        try:
            if hasattr(profile, 'account_number') and profile.account_number:
                account = Account.objects.get(account_number=profile.account_number)
                profile.account = account
                profile.save()
                print(f"Updated UserProfile {profile.id}: {profile.account_number} -> Account {account.id}")
        except Account.DoesNotExist:
            print(f"Warning: No account found for UserProfile {profile.id} with account_number {profile.account_number}")
            profile.delete()

def reverse_conversion(apps, schema_editor):
    """Reverse the conversion if needed"""
    # We won't implement reverse since we're fixing forward only
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_account_alter_usersettings_account'),
    ]

    operations = [
        migrations.RunPython(convert_account_numbers, reverse_conversion),
    ]
