# Generated by Django 5.2.7 on 2026-02-04 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSpecDump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('loan', 'Loan Application'), ('insurance', 'Insurance Application'), ('escrow', 'Escrow Application')], max_length=50)),
                ('product_subtype', models.CharField(blank=True, max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('document_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(default='web', max_length=100)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('processed', 'Processed'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='collected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'created_at'], name='kyc_spec_ky_product_156f40_idx'), models.Index(fields=['user_email'], name='kyc_spec_ky_user_em_0a9a51_idx'), models.Index(fields=['status'], name='kyc_spec_ky_status_bd2e38_idx')],
            },
        ),
    ]
